# Generated by Django 2.2.1 on 2019-06-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0003_auto_20190613_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__first_name', '-created_at'], 'permissions': [('list_profile', 'Pode Listar Perfils')], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfils'},
        ),
    ]
