# Generated by Django 2.2.1 on 2019-06-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='datetime',
            field=models.DateTimeField(default='2019-01-01', verbose_name='Data/Hora'),
            preserve_default=False,
        ),
    ]
