# Generated by Django 2.2.1 on 2019-06-05 03:03

from django.db import migrations, models
import gringo_tv.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_config_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=gringo_tv.core.models.get_config_path, verbose_name='Imagem'),
        ),
    ]
