# Generated by Django 2.2.1 on 2019-06-16 22:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190605_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem'),
        ),
    ]
